#!/usr/bin/env python3
"""
ica53_tc_to_npz.py
==================

Read the ICA-53 timecourse NIfTIs referenced by the MDD master CSV
(`ica53_tc` column) and pack them, together with selected metadata columns,
into a single compressed .npz. Arrays inside the .npz are named by their CSV
column name (`ica53_tc`, `id`, `Diagnosis`, `Sex`, `Age`, `Education`,
`HAMDTotal17`, `HAMATotal`, `HAMD3`).

Edit the CONFIG block and run:  python ica53_tc_to_npz.py

Timecourses can differ in length; they are cropped to the minimum length across
the loaded set so the result is a uniform `(N, T_min, 53)` array.

Also writes `<npz>_legend.md` next to the archive: counts for categorical labels
(`Diagnosis`, `Sex`) and N/missing/min/max/mean/std for the continuous scores.

Needs numpy, pandas, nibabel.
"""

import os
import numpy as np
import pandas as pd
import nibabel as nib

# ── CONFIG ────────────────────────────────────────────────────────────────────
IN_CSV = "data/mdd_master.csv"     # master CSV produced by build_mdd_master_csv.py (in data/)
OUT_NPZ = "data/mdd_ica53_tc_superclean.npz"   # saved into the data/ subdirectory
TC_COL = "ica53_tc"                # timecourse path column to load
FILTER_COL = "in_super_clean"      # keep only rows where this column is truthy; None = no filter
META_COLS = ["id", "Diagnosis", "Sex", "Age", "Education",
             "HAMDTotal17", "HAMATotal", "HAMD3"]
CATEGORICAL = ["Diagnosis", "Sex"]     # summarised as counts; other META_COLS (except id) = continuous
LABELS = {"Diagnosis": {1: "MDD", 0: "HC"}, "Sex": {1: "Male", 2: "Female"}}
LIMIT = None                       # int for a quick test (e.g. 20); None = all
# ──────────────────────────────────────────────────────────────────────────────


def load_tc(path):
    """Load one timecourse NIfTI -> float32 (T, 53)."""
    return np.squeeze(np.asarray(nib.load(path).get_fdata(), dtype=np.float32))


def write_legend(df, out_md, tc_shape):
    """Auto-generate a stats legend (TC shape + categorical counts + continuous summaries)."""
    n, t_min = tc_shape[0], tc_shape[1]
    rows = [("ica53_tc", "Shape (N, T, components)",
             f"({tc_shape[0]}, {tc_shape[1]}, {tc_shape[2]})")]  # (Category, Statistic/Label, Value)

    for col in CATEGORICAL:
        if col not in df.columns:
            continue
        s = pd.to_numeric(df[col], errors="coerce")
        vc = s.value_counts(dropna=False)
        keys = sorted(k for k in vc.index if pd.notna(k)) + [k for k in vc.index if pd.isna(k)]
        for k in keys:
            if pd.isna(k):
                rows.append((col, "Count missing", int(vc[k])))
            else:
                lab = LABELS.get(col, {}).get(int(k))
                name = f"{lab} ({int(k)})" if lab else str(int(k))
                rows.append((col, f"Count {name}", int(vc[k])))

    for col in [c for c in META_COLS if c not in CATEGORICAL and c != "id"]:
        if col not in df.columns:
            continue
        x = pd.to_numeric(df[col], errors="coerce")
        v = x.dropna()
        rows.append((col, "N", int(v.shape[0])))
        rows.append((col, "Missing", int(x.isna().sum())))
        if len(v):
            rows += [(col, "Min", round(float(v.min()), 2)),
                     (col, "Max", round(float(v.max()), 2)),
                     (col, "Mean", round(float(v.mean()), 2)),
                     (col, "Std Dev", round(float(v.std()), 2))]

    if "Age" in df.columns:
        a = pd.to_numeric(df["Age"], errors="coerce").dropna()
        if len(a):
            binned = pd.cut(a, bins=3).value_counts().sort_index()
            for i, (iv, cnt) in enumerate(binned.items()):
                rows.append(("Age Bins", f"Count Bin {i} ({iv.left:.1f}-{iv.right:.1f})", int(cnt)))

    arc = os.path.basename(OUT_NPZ)
    md = [f"# {arc} — metadata legend", "",
          f"Auto-generated by `ica53_tc_to_npz.py`. Summary of the metadata arrays in "
          f"`{arc}` (N = {n} subjects; `ica53_tc` cropped to T = {t_min}). `id` omitted. "
          f"HAMD/HAMA scores are recorded for MDD patients only (hence high missing); "
          f"a blank `Diagnosis` = schizophrenia/bipolar subject.", "",
          "| Category | Statistic/Label | Value |", "| :--- | :--- | ---: |"]
    md += [f"| {c} | {s} | {v} |" for c, s, v in rows]
    with open(out_md, "w") as f:
        f.write("\n".join(md) + "\n")


def main():
    df = pd.read_csv(IN_CSV)
    if TC_COL not in df.columns:
        raise SystemExit(f"'{TC_COL}' not in {IN_CSV}")

    # restrict to a QC tier (e.g. super_clean) via a boolean flag column
    if FILTER_COL:
        if FILTER_COL not in df.columns:
            raise SystemExit(f"'{FILTER_COL}' not in {IN_CSV}")
        truthy = df[FILTER_COL].map(
            lambda v: str(v).strip().lower() in ("true", "1", "1.0", "yes"))
        df = df[truthy].copy()
        print(f"Filtered to {FILTER_COL}: {len(df)} rows")

    # keep only rows that actually reference a timecourse file
    df = df[df[TC_COL].notna() & (df[TC_COL].astype(str).str.strip() != "")].copy()
    if LIMIT:
        df = df.head(LIMIT)
    df = df.reset_index(drop=True)

    tcs, keep = [], []
    for i, p in enumerate(df[TC_COL]):
        try:
            if not os.path.exists(p):
                raise FileNotFoundError(p)
            tcs.append(load_tc(p))
            keep.append(i)
        except Exception as e:
            print(f"  skip [{df.iloc[i]['id']}]: {e}")
    df = df.iloc[keep].reset_index(drop=True)
    if not tcs:
        raise SystemExit("No timecourses could be loaded.")

    # crop every timecourse to the minimum length so they stack uniformly
    lengths = [t.shape[0] for t in tcs]
    t_min, t_max = min(lengths), max(lengths)
    n_crop = sum(1 for L in lengths if L > t_min)
    print(f"Timecourse lengths: min={t_min} max={t_max} (N={len(tcs)})")
    if t_max > t_min:
        print(f"  cropping {n_crop} subject(s) to T={t_min} "
              f"(trimming up to {t_max - t_min} timepoints from the end)")
    else:
        print("  all timecourses equal length; no cropping needed")
    tc_arr = np.stack([t[:t_min] for t in tcs]).astype(np.float32)   # (N, t_min, 53)

    # metadata arrays, keyed by CSV column name
    out = {TC_COL: tc_arr}
    for c in META_COLS:
        if c not in df.columns:
            print(f"  WARN: column '{c}' not in CSV — skipped")
            continue
        if c == "id":
            out[c] = df[c].astype(str).to_numpy()
        else:
            out[c] = pd.to_numeric(df[c], errors="coerce").to_numpy(dtype=np.float32)

    os.makedirs(os.path.dirname(OUT_NPZ) or ".", exist_ok=True)
    np.savez_compressed(OUT_NPZ, **out)

    # summary
    print(f"Saved {OUT_NPZ}  (N = {len(df)} subjects)")
    print(f"  {TC_COL}: stacked array {tc_arr.shape} {tc_arr.dtype}")
    for c in META_COLS:
        if c in out:
            print(f"  {c:12s}: {out[c].shape} {out[c].dtype}")

    # auto-generate the stats legend next to the archive: <npz>_legend.md
    out_legend = os.path.splitext(OUT_NPZ)[0] + "_legend.md"
    write_legend(df, out_legend, tc_arr.shape)
    print(f"Wrote legend -> {out_legend}")


if __name__ == "__main__":
    main()
